name: training_timer
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  intl: ^0.18.0
  flutter_riverpod: ^2.2.0
  go_router: ^13.0.1
  gap: ^3.0.1
  circular_countdown_timer: ^0.2.3
  audioplayers: ^3.0.1
  keep_screen_on: ^2.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  generate: true

  assets:
    - images/icons/
    - sounds/end.ogg
    - sounds/start.ogg
    - sounds/whistle.ogg


