name: training_timer
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_riverpod: ^2.2.0
  go_router: ^14.8.1
  gap: ^3.0.1
  circular_countdown_timer: ^0.2.3
  keep_screen_on: ^4.0.0
  flutter_localizations:
    sdk: flutter
  assets_audio_player:
    git:
      url: https://github.com/hmukwana/Flutter-AssetsAudioPlayer
  animated_emoji: ^3.1.0
  flutter_native_splash: ^2.2.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  generate: true

  assets:
    - images/icons/
    - sounds/end.ogg
    - sounds/start.ogg
    - sounds/whistle.ogg
    - packages/animated_emoji/lottie/fireworks.json


